name: Catchup deployment state

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Set to true for dry run, false for actual deployment'
        required: false
        type: boolean
        default: true

env:
  DRY_RUN_PARAM: ${{ inputs.dry_run && '--dry-run' || '' }}

jobs:
  catchup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-ftp

      - name: Catchup git-ftp
        run: |
          git-ftp catchup --insecure ${{ env.DRY_RUN_PARAM }} -u ${{ secrets.FTP_USER }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}